version: "3.7"
services:
    app:
        build:
            args:
                user: "vukm"
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: crawl-img
        container_name: crawl-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker-compose/supervisor/config:/etc/supervisor/conf.d/
        networks:
            - crawl

    db:
        image: mysql:5.7
        container_name: crawl-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3317:3306
        volumes:
            - crawl-db:/var/lib/mysql
        networks:
            - crawl

    nginx:
        image: nginx:alpine
        container_name: crawl-nginx
        restart: unless-stopped
        ports:
            - 8017:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - crawl

volumes:
    crawl-db:
networks:
    crawl:
        driver: bridge
